apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  .env: "REFUQUJBU0VfVVJMPXBvc3RncmVzOi8vb2Frc2RvYWtvZHNrc2EKQVdTX1NFQ1JFVD0xMjNpbzFpM28xMmkzbwpQT1JUPTMwMDAKUFVCTElDX0tFWT0xMjNrbGFkc2tvYWRzCkpXVF9TRUNSRVQ9MTJhc29rZGFzaW85MQ=="
